# Generated by Django 5.0.6 on 2026-02-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_player_first_name_player_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerID',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
