# Generated by Django 5.0.6 on 2026-02-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_player_playerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staffID',
            field=models.CharField(blank=True, default='', max_length=20, unique=True),
        ),
    ]
