# Generated by Django 5.0.6 on 2026-02-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_staff_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='playerID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
