# Generated by Django 5.0.6 on 2026-04-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_player_playerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
