# Generated by Django 5.0.6 on 2026-04-19 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_player_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('training_type', models.CharField(choices=[('Attacking', 'Attacking'), ('Defending', 'Defending'), ('Passing', 'Passing'), ('Fitness', 'Fitness'), ('Match Sim', 'Match Sim')], max_length=15)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('player_notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.player')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
            options={
                'unique_together': {('player', 'training')},
            },
        ),
    ]
